### ISSUE TITLE
Clarification on server config.

### ISSUE THREAD

**Issue by Bungpiece** [simlrh/OSVR-fusion#1] opened 2016-08-14 21:28 UTC
Hi I was hoping to get some clarification on setting up my server config. I'm trying to use your fusion plugins to add kinect positional tracking much like your provided example.
I'm running into issues specifically with the orientation line. 
`"orientation": "/je_nourish_openhmd/Oculus Rift (Devkit)/semantic/hmd"`
Can I assume that `Oculus Rift (Devkit)` is intended to be changed to the name of the .json from the display folder such as `Oculus_Rift_DK2`? 
I've installed your open hmd plugin the same as the rest but osvr server always returns:
`Could not resolve source for /je_nourish_openhmd/Oculus_Rift_DK2/semantic/hmd` I have tried it as it appears unaltered in your readme too but the results are the same.
Tracker viewer will display my hands and head but the head does not rotate. The render example crashes if I'm being tracked presently with these plugins installed, but is fine if I'm just using the official com_osvr_OculusRift plugin. I would rather use this plugin but am unsure how to enter it into the orientation line in the config. Thank you for any help you can offer.

**Comment by simlrh** [comment] 2016-08-21 15:17
Hi, do you also have https://github.com/simlrh/OSVR-OpenHMD installed?

If so, I will send you a debug version of that plugin to figure out what name is supposed to be used for DK2 if that's ok. Closing this issue as the problem is with the other plugin, I'll open an issue over there when I have time to sort this.

**Closed as completed by simlrh** 2016-08-21 15:17 UTC

**Comment by Bungpiece** [comment] 2016-08-21 15:35
Yes I did have your open hmd plugin installed. Sorry I Just realised that I'd posted this in the wrong place, but this was where you had the most comprehensive server_config. Happy to try and help. In the mean time I seem to have got it working with the official osvr plugin using:
"orientation": "/com_osvr_OculusRift/OculusRift0/semantic/hmd",
